[WIP] feat: flash mint
opynfinance/squeeth-monorepo pull request #173
Opened 2022-02-16 16:53 UTC by haythem96

# feat: flash mint

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-02-20 18:56 UTC, aleone requested changes
- few suggested changes on way to test
- should test slippage and ensure its correct
- ensure refund is roughly slippage
- fix fee calculation (remove or take into account)

2022-02-20 18:56 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      // expect(vaultBefore.collateralAmount.add(collateralAmount).eq(vaultAfter.collateralAmount)).to.be.true
this is failing because of the fee

2022-02-20 18:56 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      // expect(vaultBefore.collateralAmount.add(collateralAmount).eq(vaultAfter.collateralAmount)).to.be.true
can either remove fee or calculate expected fee and subtract it from collateral in controller and collateral in vault

2022-02-20 18:56 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      const mintWSqueethAmount = ethers.utils.parseUnits('2')
think should make this larger as we will have to update tests to take into account 6.9 eth min collateral (might as well make it work now)

2022-02-20 18:56 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      await controllerHelper.connect(depositor).flashWMint(0, mintWSqueethAmount, collateralAmount, {value: value});
think we should test this in a way where we set a slippage and ensure it matches

2022-02-20 18:56 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      const value = collateralAmount.div(2).add(collateralAmount.div(3))
I think to calculate value we should:
- pick a oSQTH amount
- figure out the CR we want (say 150% or 200% or whatever)
- determine the amount of collateral that corresponds to 
- determine the uniswap price
- figure out how much ETH the set oSQTH will be sold for + some set slippage
- figure out what msg.value needs to be from collateral - expectedEthProceeds * (1-slippage)

2022-02-21 18:11 UTC, aleone approved these changes
I still think should calculate the exact expected eth out amount and use that to ensure that the refund is correct

2022-02-21 18:11 UTC, aleone commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      const ethAmountOut = mintWSqueethAmount.mul(squeethEthPrice).div(one)
i still think its worth checking the exact expected out here (ie including price impact on uniswap), but lmk what you think

that way we can compare and ensure that the user is refunded value - ethAmountOut, which means that 0 of the slippage was used (which is to be expected when testing)

2022-02-21 18:50 UTC, aleone requested changes
suggestion on how to do slippage control

2022-02-21 19:04 UTC, alpinechicken commented on packages/hardhat/contracts/periphery/ControllerHelper.sol
> +        uint256 swapedCollateralAmount,
*swappedCollateralAmount?

2022-02-23 17:40 UTC, aleone commented on packages/hardhat/contracts/periphery/ControllerHelper.sol
> +            if (address(this).balance > 0) {
IMO this needs to be checking weth balance as we convert all to weth and then might pay less than the msg.value

2022-02-23 17:41 UTC, aleone requested changes
we need to refund unused WETH to the user

if the slippage is not used they should get a refund

test is not testing right thing

2022-03-04 18:45 UTC, aleone approved these changes

2022-03-04 18:45 UTC, aleone commented on packages/hardhat/contracts/periphery/ControllerHelper.sol
> +            if (address(this).balance > 0) {
what happens if we try to send 0 ETH?

for pretty much every case there will be some remaining eth in the contract (at least 1 wei), so is it cheaper to just send address(this).balance to the user ever time and not check, or will it revert?

2022-03-04 18:56 UTC, aleone commented
lgtm, but do think we should check that the user gets the expected eth amount back in tests (maybe you wanted to do in a test PR improvement later or something)

2022-03-06 12:57 UTC, merged

2022-03-07 04:45 UTC, KMKoushik commented on packages/hardhat/test/integration-tests/periphery/controller-helper.ts
> +      await wSqueeth.connect(owner).approve(swapRouter.address, constants.MaxUint256)
Doubt. Why do we need this? Is it to get `exactInputSingle`?