Fix loading in crab positions
opynfinance/squeeth-monorepo pull request #230
Opened 2022-03-10 17:22 UTC by adam5909099

## Description
Fix loading state of crab positions.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-03-10 17:24 UTC, adam5909099 commented on packages/frontend/src/context/crabStrategy.tsx
> +  const { value: userCrabBalance, loading: userCrabBalanceLoading } = useTokenBalance(crabStrategy, 5, 18, !ready)
We need to handle crab balance loading as well to get rid of flickering.

2022-03-10 17:26 UTC, adam5909099 commented on packages/frontend/src/context/crabStrategy.tsx
> +    loading: loading || !ready || userCrabBalanceLoading || currentEthLoading,
It takes about 200ms to load calculate Eth. We need to handle the loading of current eth as well.

2022-03-10 17:29 UTC, adam5909099 commented on packages/frontend/src/hooks/contracts/useTokenBalance.ts
> +  userTokenBalance: (token: string) => ['userTokenBalance', token],
Having token (address) as a key is critical because the crab loading state was mixed with another loading state of getting the token.

2022-03-10 17:30 UTC, adam5909099 commented on packages/frontend/src/hooks/contracts/useTokenBalance.ts
> -      staleTime: 15000,
Instead of hard coded stale time, we'll wait until the query is ready to start fetching

2022-03-11 06:32 UTC, alexisgauba requested changes
taking a while for the crab box to show up for me - would be good if we could show the box and show loading states in the box so users aren't confused about where their crab position went 

https://user-images.githubusercontent.com/13340486/157814846-ab8171a1-96ca-4a8d-9c9b-c6a203a2f42f.mov

2022-03-14 15:11 UTC, adam5909099 commented
@alexisgauba Thanks for the recording, I updated PR as you mentioned.

2022-03-14 17:58 UTC, alexisgauba commented
> https://continuouscall-git-issue-209-positions-loading-opynfinance.vercel.app

great! this is much better. It did take about 45sec to load for me, is this being handled in the jotai PR or is that something we should address here as well

2022-03-14 19:56 UTC, alexisgauba requested changes

2022-03-14 19:56 UTC, alexisgauba commented on packages/frontend/src/hooks/contracts/useTokenBalance.ts
> +  if (token === '0xbffbd99cfd9d77c49595dfe8eb531715906ca4cf') {
what's this doin? if we are using addresses we should use constants

2022-03-15 20:22 UTC, alexisgauba approved these changes

2022-03-15 22:05 UTC, block902 approved these changes
Tested on my side and looks good!

2022-03-15 22:07 UTC, merged