Update crab position in deposit UI
opynfinance/squeeth-monorepo pull request #253
Opened 2022-03-21 17:03 UTC by adam5909099

# Task:
https://github.com/opynfinance/squeeth-monorepo/issues/212

## Description
Show no crab position if the user doesn't have and a loading state if loading.
![image](https://user-images.githubusercontent.com/59410529/159325614-c4559dd5-6174-442c-805e-46196640180f.png)

Fixes # (issue)
https://github.com/opynfinance/squeeth-monorepo/issues/212

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested
Go to strategies page with no crab position and check if it shows no position

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-03-21 23:28 UTC, KMKoushik commented
PnL% is not shown
<img width="631" alt="Screenshot 2022-03-22 at 10 28 27 AM" src="https://user-images.githubusercontent.com/24666922/159379372-4ae4ffcd-f177-4154-a695-72bdaf727833.png">

2022-03-21 23:32 UTC, KMKoushik requested changes
I am not sure why, but PnL % is not shown in preview but working in live

2022-03-23 08:50 UTC, KMKoushik commented on packages/frontend/src/components/Trade/index.tsx
> +      display: 'block',
Is this used?

2022-03-23 08:51 UTC, KMKoushik approved these changes
Jus check if the added styles are used. LGTM

2022-03-23 09:26 UTC, EstherSeyi approved these changes
LGTM

2022-03-23 22:18 UTC, merged