test: add e2e strategy test
opynfinance/squeeth-monorepo pull request #315
Opened 2022-04-08 08:20 UTC by yichiehliu

# Task:

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-04-13 00:27 UTC, KMKoushik requested changes

2022-04-13 00:27 UTC, KMKoushik commented on packages/frontend/tests1/e2e/07-strategy.spec.js
> +import TradePage from '../pages/trade'
@yichiehliu Why this file is in a different location? Can we move it with other test fikes

2022-04-20 13:10 UTC, KMKoushik commented
@yichiehliu Strategy testing is not working for me

<img width="1062" alt="Screen Shot 2022-04-20 at 11 10 13 pm" src="https://user-images.githubusercontent.com/24666922/164237715-c8796eae-f1df-4aff-9a31-63f1f833b1b2.png">

2022-04-22 09:38 UTC, yichiehliu commented
> @yichiehliu Strategy testing is not working for me
> 
> <img alt="Screen Shot 2022-04-20 at 11 10 13 pm" width="1062" src="https://user-images.githubusercontent.com/24666922/164237715-c8796eae-f1df-4aff-9a31-63f1f833b1b2.png">

It's failing because the strategy cap has been reached on ropsten, is it anyway to change the cap?

2022-12-29 22:16 UTC, closed without merging