fix: max debt amount to be total deb if debt if less than user oSQTH …
opynfinance/squeeth-monorepo pull request #319
Opened 2022-04-08 10:19 UTC by yichiehliu

…balance

# Task:

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-04-12 09:27 UTC, KMKoushik commented
@yichiehliu If my short amount is greater than the balance, it should use my balance as max.

https://user-images.githubusercontent.com/24666922/162928127-b9424f03-a4ef-496f-8a54-5217623838cf.mov

2022-04-12 09:28 UTC, KMKoushik requested changes
Check the above commented case

2022-04-12 23:59 UTC, KMKoushik approved these changes
LGTM

2022-04-13 12:23 UTC, EstherSeyi approved these changes

2022-04-13 14:04 UTC, merged