feat: Adds close short component
opynfinance/squeeth-monorepo pull request #321
Opened 2022-04-08 18:19 UTC by EstherSeyi

…onorepo into fe/flash-swap-wburn# Task:

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

2022-07-01 17:00 UTC, daryakaviani requested changes

2022-07-05 08:45 UTC, adam5909099 commented on packages/frontend/src/components/Trade/Short/CloseShort.tsx
> +      (vault?.shortAmount && amount.gt(vault.shortAmount))
```suggestion
      (vault?.shortAmount && amount.gt(vault.shortAmount))
```

2022-07-07 06:14 UTC, alexisgauba commented
Was getting this issue where it wouldn't let me partial close, just defaulted back to full close. Fixed itself after a couple of refreshes

https://user-images.githubusercontent.com/13340486/177704375-e0c26767-b15c-4402-96d4-48d017cfbf31.mov

2022-07-08 01:28 UTC, adam5909099 commented
@alexisgauba It's because useAppEffect for setting close type to full called periodically. I fixed it, so it should be good now.

2022-12-29 22:17 UTC, closed without merging