[WIP] Crab V2 Subgraph Frontend
opynfinance/squeeth-monorepo pull request #609
Opened 2022-07-22 20:47 UTC by daryakaviani

2022-07-23 06:04 UTC, KMKoushik requested changes
LGTM with some comments. Thanks for helping me out

2022-07-23 06:04 UTC, KMKoushik commented on packages/frontend/src/hooks/useCrabPosition/useCrabPosition.ts
> +  const { depositedEth, usdAmount: depositedUsd } = useAppMemo(() => {
This seems good with one exception. Migrated users will not have a deposit tx. so this PnL / position might be wrong for users. We should track migration events too and consider them as deposits.  @alexisgauba What do you think will be the right thing here?

2022-07-23 06:04 UTC, KMKoushik commented on packages/frontend/src/components/Strategies/Crab/CapDetailsV2.tsx
> +import CustomLinearProgress from '@components/CustomProgress'
Can we create a new folder crabV2, so we clearly know the distinction?

2022-07-23 20:25 UTC, aparnakr approved these changes
The changes look fine to me, its working fine on the UI. 

The only thing I wonder is why its showing all the 27 files and changes which are already on the branch again. Have you rebased it?

2022-07-25 00:18 UTC, KMKoushik commented
Be merged #614

2022-07-25 00:18 UTC, closed without merging