ui: update funding to daily premium to test
opynfinance/squeeth-monorepo pull request #669
Opened 2022-10-13 00:35 UTC by alexisgauba

# Task:

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

2022-10-13 21:59 UTC, reganomalley commented on packages/frontend/src/components/Charts/LongChart.tsx
> +            Premiums are is paid out of your position, similar to selling a small amount of squeeth as you earn
typo here. should premiums are paid out

2022-10-13 22:01 UTC, reganomalley commented on packages/frontend/src/components/Trade/Long/BreakEven.tsx
> +        tooltip={`To breakeven ETH to needs to move to ${breakEven.toFixed(3)}% in one day, since current premiums is
typo here. should be "since current premiums are"

2022-10-13 22:02 UTC, reganomalley requested changes
just a couple typos. i left comments!

2022-10-14 23:21 UTC, alexisgauba commented
> just a couple typos. i left comments!

tyty! updated

2022-10-16 21:36 UTC, KMKoushik approved these changes

2022-10-16 21:51 UTC, reganomalley approved these changes

2022-10-17 20:38 UTC, merged