Feat/add squeeth ref vol
opynfinance/squeeth-monorepo pull request #677
Opened 2022-10-20 15:02 UTC by DemolaJames

# Task:

## Description

Added Squeeth Ref vol to main trade page 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

2022-10-20 15:38 UTC, DemolaJames commented
![Screenshot 2022-10-20 at 16 35 28](https://user-images.githubusercontent.com/66267188/196994231-65436b33-43ae-4a8f-a514-1aec4b4edaf9.png)

2022-10-20 21:50 UTC, KMKoushik approved these changes

2022-10-21 00:17 UTC, aleone commented
@haythem96 I'm seeing 78% vol on the f/e, that is wrong, right?  Is it not updating in the db?

2022-10-22 03:59 UTC, alexisgauba requested changes

2022-10-22 03:59 UTC, alexisgauba commented on packages/frontend/src/constants/enums.ts
> +  osqthRefVol = 'Squeeth reference volatility based on deribit options and squeeth replicating portfolio. Squeeth ref vol is calculated/refreshed every 5 minutes..Click the link icon to learn more',
```suggestion
  osqthRefVol = 'Squeeth reference volatility based on deribit options and squeeth replicating portfolio. Squeeth ref vol is calculated/refreshed every 5 minutes.',
```

2022-10-22 03:59 UTC, alexisgauba commented on packages/frontend/src/constants/enums.ts
> +  osqthRefVol = 'Squeeth reference volatility based on deribit options and squeeth replicating portfolio. Squeeth ref vol is calculated/refreshed every 5 minutes..Click the link icon to learn more',
The link icon should be self-explanatory, if its not we need a better visual

2022-10-22 03:59 UTC, alexisgauba commented on packages/frontend/src/constants/index.ts
> +export const squeethRefVolDocLink = 'https://colab.research.google.com/drive/1HTM_2j0jmda9tzN_uskBPz9Rpma8Lp3C'
is this the right link or is there an update paper / medium @alpinechicken @southamerica ?

2022-10-22 04:02 UTC, alexisgauba commented
I'm seeing 75.57% on the site but 64.9% on Joe's colab, looks like the FE is off? Even with the 5 min gap this seems quite off

<img width="580" alt="Screen Shot 2022-10-21 at 9 02 20 PM" src="https://user-images.githubusercontent.com/13340486/197318217-0b7d89fb-057b-4ae2-9558-e71983791536.png">

<img width="815" alt="Screen Shot 2022-10-21 at 9 02 43 PM" src="https://user-images.githubusercontent.com/13340486/197318234-2df69976-4739-4ad0-98ad-e925c82de858.png">

2022-10-26 22:54 UTC, aleone commented
The tooltip says 3 minutes, it is not 5 minutes, correct?  Lets make sure we have the correct refresh interval before merging.

2022-10-27 18:04 UTC, alexisgauba approved these changes

2022-10-27 19:37 UTC, merged