Second Flashdeposit Test
opynfinance/squeeth-monorepo pull request #697
Opened 2022-10-31 21:30 UTC by daryakaviani

Added a test for 2 consecutive flashdeposits. Found an issue with calculations (potentially using wdiv(12) where unnecessary).

2022-11-02 08:50 UTC, haythem96 commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +            0,
I think we can set those to non-zero values, like getting the current prices from the pool and add a bit of slippage

2022-11-02 08:51 UTC, haythem96 commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        }(ethToCrabSecond, 0, 0, 3000);
Same here

2022-11-02 08:52 UTC, haythem96 commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        );
Maybe add assert for user bull balance

2022-11-02 08:52 UTC, haythem96 reviewed
LGTM, added few comments.

2022-11-02 21:50 UTC, haythem96 commented on packages/bull-vault/src/LeverageBull.sol
> +        uint256 usdcToBorrow = IEulerDToken(dToken).balanceOf(address(this)).wmul(_bullShare).wdiv(ONE.sub(_bullShare));
Yeah this make sense, IEulerDToken(dToken).balanceOf() is in 6 decimals already

2022-11-02 21:51 UTC, haythem96 commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +
Add an assert for depositor bull balance check

2022-11-02 21:54 UTC, haythem96 commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +    function _calcCollateralAndBorrowAmount(uint256 _crabToDeposit)
The extra 1e12 div is not fixed here

2022-11-02 22:05 UTC, haythem96 requested changes
Need to remove the additional 1e12 div in test file

2022-11-03 19:13 UTC, daryakaviani commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +    function _calcCollateralAndBorrowAmount(uint256 _crabToDeposit)
I fixed it in the else case I believe.

2022-11-04 00:11 UTC, haythem96 approved these changes
LGTM

2022-11-04 19:28 UTC, alpinechicken commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        assertEq(
Need to check user eth balance

2022-11-04 19:30 UTC, alpinechicken commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        assertEq(
should be getting a small refund

2022-11-04 19:41 UTC, alpinechicken commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        assertEq(
Add assert for user eth balance

2022-11-04 19:46 UTC, alpinechicken commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        assertEq(
We should be able to get an exact value for this if we use uniswap quoter contract get exact eth out for squeeth and usdc. Same for flashdeposit.

2022-11-04 20:10 UTC, alpinechicken commented on packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
> +        );
assert for user eth balance as above

2022-11-04 20:15 UTC, alpinechicken requested changes
generally lgtm. I think we probably need an assert for user eth balance for flashWithdraw/flashDeposit because there will generally be refunds

2022-11-06 13:51 UTC, merged