[WIP] Cookies setup
opynfinance/squeeth-monorepo pull request #714
Opened 2022-11-07 22:20 UTC by DemolaJames

# Task:

## Description

Add cookies setup to FE 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

2022-11-15 22:48 UTC, KMKoushik approved these changes

2022-11-15 22:48 UTC, KMKoushik commented on packages/frontend/src/hooks/useCookies/canStoreCookies.ts
> +import { CookieNames } from "."
These are not hooks. Can you move all the functions to utils folder in `cookies.ts`?

2022-11-15 22:48 UTC, KMKoushik commented on packages/frontend/src/components/SettingsMenu.tsx
> +      <Modal
Can we make it a little bigger? It's so small right now?

2022-11-15 22:48 UTC, KMKoushik commented on packages/frontend/src/components/SettingsMenu.tsx
> +
Should we call initialize after accepting?

2022-11-15 22:48 UTC, KMKoushik commented on packages/frontend/src/components/SettingsMenu.tsx
> +  const AcceptCookie = () => {
Should be `acceptCookie`

2022-11-15 22:48 UTC, KMKoushik commented on packages/frontend/src/hooks/useCookies/setCookie.ts
> +        initializeAmplitude()
Oh okay, it's updated here!

2022-11-18 05:33 UTC, alexisgauba commented
Is there a way visually to make it a lot smaller? Feel like most sites just have a thing in the corner - looks pretty clunky right now 

<img width="1335" alt="Screen Shot 2022-11-17 at 9 31 29 PM" src="https://user-images.githubusercontent.com/13340486/202627925-03a335c0-4798-4665-9b78-d3ab1ebc32cb.png">

<img width="575" alt="Screen Shot 2022-11-17 at 9 31 49 PM" src="https://user-images.githubusercontent.com/13340486/202627985-d4910a6e-8dd5-40f1-8e16-db5b54efbf82.png">

<img width="675" alt="Screen Shot 2022-11-17 at 9 26 51 PM" src="https://user-images.githubusercontent.com/13340486/202627295-761d75fc-610a-46cc-a103-a410976adf02.png">

2022-11-18 05:39 UTC, alexisgauba requested changes
ui/ux needs to be improved

2022-11-18 19:02 UTC, tamtam3000 commented
Cookie box text needs to be changed to: We use cookies to support technical features that enhance your user experience and analyze frontend traffic. To learn more about these methods, including how to disable them, view our **Privacy Policy**. 

Note, _there is no separate cookie policy._ _Only a Privacy Policy_ that has an additional tracker / cookie section. Here is a link to the google doc with the final draft of the updated privacy policy: https://docs.google.com/document/d/1Y5Eg46AGbZJuOL0yNbD2g62uv39yi2Ppq47zeMg-9m4/edit. 

So remove the Cookie policy entirely from the frontend. 

**For the Privacy Policy text:** 

The Last Updated section needs to be updated to the date the PR is merged so, November ___ , 2022. 

Follow the google doc I sent that also has these notes. For example, in Section 4, the Analytics section, you need to add a link that will jump to a later section of the privacy policy page, where the text states, og to section 6.2 “Cookies the Interface Uses.”

**Privacy Policy Format:** 


<img width="983" alt="Screenshot 2022-11-18 at 1 48 17 PM" src="https://user-images.githubusercontent.com/90271088/202780175-68c092fc-f70e-4430-8264-99c14e5b4e5b.png">

The above section needs to be spaced out as in the google doc linked above so that each tracker type is in its own paragraph. I highlighted this in the docs so it's clear. 

6.2 Cookies the Interface Uses 

I updated the format in this section and text slightly. Please refer to the google doc linked above. 

Let me know if you have any questions on text or format related to the above.

2022-11-21 18:25 UTC, merged