fuzz-testing: euler deposit and withdraw
opynfinance/squeeth-monorepo pull request #745
Opened 2022-11-16 23:17 UTC by haythem96

# Task: euler deposit and withdraw

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

2022-11-19 00:39 UTC, alpinechicken commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        uint256 eulerUsdcBalance = IERC20(usdc).balanceOf(euler);
why not use dToken.balanceOfUnderling?

2022-11-19 01:44 UTC, alpinechicken approved these changes
lgtm

2022-11-21 21:29 UTC, aleone requested changes
Something funky going on with ```        uint256 debtAmount = IEulerDToken(dToken).balanceOf(auction); ```

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(usdcBalanceAfter.sub(IERC20(usdc).balanceOf(auction)), 0);
i dont get this assertion - aren't we asserting that the usdc balance doesn't change when we repay?

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(usdcBalanceAfter.sub(IERC20(usdc).balanceOf(auction)), 0);
how is this passing?

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        IEulerMarkets(eulerMarketsModule).enterMarket(0, weth);
same comment

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(IEulerDToken(dToken).balanceOf(auction).sub(debtAmount), usdcToRepay);
isnt this a negative number?  or is something funky going on

debtAmount is the amount of USDC debt we have in total before we do any repayment
dToken.balanceOf(auction) is the debt amount after we repay
isnt the 2nd one by definition less than the first?

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(usdcBalanceAfter.sub(IERC20(usdc).balanceOf(auction)), usdcToRepay);
this seems to be right, but very different from the above assert, not sure why (the one that says change is 0)

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(IEulerDToken(dToken).balanceOf(auction).sub(debtAmount), usdcToRepay);
turns out       
```uint256 debtAmount = IEulerDToken(dToken).balanceOf(auction); ```

is returning 0, not sure why yet

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(usdcBalanceAfter.sub(IERC20(usdc).balanceOf(auction)), usdcToRepay);
usdcToRepay is getting set to 0 per above debtAmount issue

2022-11-21 21:29 UTC, aleone commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        assertEq(usdcBalanceAfter.sub(IERC20(usdc).balanceOf(auction)), 0);
turns out usdcToRepay is getting set to 0, so this is passing. In every test we are repaying 0 usdc

2022-11-22 11:36 UTC, haythem96 commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        IEulerMarkets(eulerMarketsModule).enterMarket(0, weth);
This PR does not have that code yet

2022-11-22 11:36 UTC, haythem96 commented on packages/bull-vault/test/fuzz-test/LeverageBullFuzzTest.t.sol
> +        IEulerMarkets(eulerMarketsModule).enterMarket(0, weth);
same

2022-12-06 19:36 UTC, aleone approved these changes

2022-12-09 23:57 UTC, merged