[WIP] tests: full rebalance when CR too low or too high
opynfinance/squeeth-monorepo pull request #751
Opened 2022-11-18 14:14 UTC by haythem96

# Task: tests: full rebalance when CR too low or too high

## Description

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

2022-11-22 03:16 UTC, aleone requested changes
the tests are reversed.

we should test the delta hitting the limit as well

I think the 2nd test isn't reverting for AB2, but for underflow due to the bug @alpinechicken  pointed out

2022-11-22 03:16 UTC, aleone commented on packages/bull-vault/test/integration-test/AuctionBullTestFork.t.sol
> +        vm.expectRevert();
why are we using an ```expectRevert()``` here instead of ```expectRevert(bytes("AB2"))```?

2022-11-22 03:16 UTC, aleone commented on packages/bull-vault/test/integration-test/AuctionBullTestFork.t.sol
> +        vm.expectRevert();
if we use ```expectRevert(bytes("AB2"))``` we get the ```ds-math-sub-underflow``` error @alpinechicken  brought up

2022-12-07 00:29 UTC, aleone commented on packages/bull-vault/src/AuctionBull.sol
> +import { console } from "forge-std/console.sol";
why so many import console.logs

2022-12-07 05:15 UTC, alpinechicken approved these changes
Needs fix from #746 and remove console logs

2022-12-11 13:47 UTC, merged