feat: split uniswap fees from price impact on bull
opynfinance/squeeth-monorepo pull request #883
Opened 2022-12-29 07:44 UTC by rushikeshakhare

# Task:

Split Uniswap fees on bull deposit/withdraw

Before

![Screenshot 2022-12-29 at 1 13 30 PM](https://user-images.githubusercontent.com/52928941/209919667-03621573-503f-4d58-a3dd-f3043c1507f3.png)

After

![Screenshot 2022-12-29 at 1 13 56 PM](https://user-images.githubusercontent.com/52928941/209919704-d9fd7ea1-49a4-4fbc-be31-f1aa01db7825.png)

## Type of change

- [x] New feature
- [ ] Bug fix
- [ ] Testing code
- [ ] Document update or config files

2022-12-29 18:58 UTC, alexisgauba requested changes
Looks like there are some issues here 
- why is it initially 0.17%? Is that to reflect that not the whole deposit hits Uniswap? 
- why does the Uniswap fee go down? 

https://user-images.githubusercontent.com/13340486/209996967-e59466e4-12b1-46b9-bebc-551035660699.mov

2022-12-29 21:45 UTC, KMKoushik commented
> Looks like there are some issues here
> 
> * why is it initially 0.17%? Is that to reflect that not the whole deposit hits Uniswap?
> * why does the Uniswap fee go down?
> 
>  Screen.Recording.2022-12-29.at.10.57.32.AM.mov

@alexisgauba 
1/
It's .17% because half of your deposit to euler through eth-usd pool, half to crab from osqth-eth pool. eth-usd = 0.05, osqth-eth = .3 and avg is .17%

2/ 
Why did the fee go down for big inputs? @rushikeshakhare

2022-12-30 06:03 UTC, rushikeshakhare commented
Fixed the uniswap fee calculation @KMKoushik @alexisgauba

2022-12-30 22:44 UTC, alexisgauba approved these changes

2023-01-03 18:39 UTC, iamoperand approved these changes

2023-01-03 20:23 UTC, merged