fix: short funding chart not showing recent data
opynfinance/squeeth-monorepo pull request #998
Opened 2023-05-17 10:53 UTC by iamoperand

# Task:
funding not updating on f/e for short squeeth since apr 24th

## Description
Checkout the comments of the linear issue

Fixes ENG-1586

## Type of change

- [ ] New feature
- [x] Bug fix
- [ ] Testing code
- [ ] Document update or config files

2023-05-22 20:30 UTC, KMKoushik approved these changes

2023-05-22 20:35 UTC, KMKoushik commented on packages/frontend/src/components/Charts/ShortFundingChart.tsx
> +          <Checkbox
Can we change this to show full history?

2023-05-22 20:41 UTC, aleone requested changes
Is there a way to have the default display include the most current data, even if we need to refetch to get the full history via checkbox?

Right now users don't see current data unless they check the box, but it seems the most important thing a user should care about is the most recent data.

Also the name of the checkbox, should maybe be "Show Full History" if thats what we can do.

2023-12-10 12:43 UTC, nikkaroraa commented
stale PR

2023-12-10 12:43 UTC, closed without merging